---
title: "Fishing operations, the observations and the code"
---

## Preamble

The primary purpose of these notes is to try to come up with a code flow that efficiently can deal with different resolutions of observations (here logbooks).

In principle there is a discrepancy true fishing operation vs what is reported, e.g. in logbooks

## Fishing operation - temporal space

Fishing operation have basically four important time events:

1. Start of deployment (t1)
2. Start of fishing operation (t2)
3. End of fishing operation / start of retrieval (t3)
4. End of deployment (t4)

The relative duration between these events can vary among gear and/or the operational environment. Examples:

* When trawling, at least in shallow waters the time between t1 and t2 is relativey shoure comparted


### Operation time

Fishing operation can be either:

* Sequential in time, where once an operation is started it is completed before the next operation takes place
  * All operation that do not "require" soak time fall under this operation (trawling, jigging, ...)
    * In this case all operations are completed within a trip.
  * Soak time operation may fall under this umbrella, like e.g. a longline is set out and retrieved before the next setting takes place.
    * In this case the start of the operation may be in a different trip than the completion of the operation.
* Non-sequential in time, where one operation can be started but not completed prior to another operation is started.
   * In this case:
      * All operations could be completed within a trip
      * Some operation could be completed within a trip
      * None of the operation could be completed within a trip.
   
   


```{r}
library(tidyverse)
  library(omar)
  con <- connect_mar()
  tbl_mar(con, "adb.trip_v") |> 
    filter(year(departure) == 2024) |> 
    select(trip_id, 
           vid = vessel_no,
           T1 = departure,
           hid1 = departure_port_no,
           T2 = landing,
           hid2 = landing_port_no) |> 
    # only trips were some logbook recorded
    left_join(tbl_mar(con, "adb.station_v") |> 
                select(trip_id,
                       station_id,
                       gid = gear_no,
                       t1 = fishing_start,
                       t2 = fishing_end,
                       lon1 = longitude,
                       lat1 = latitude,
                       lon2 = longitude_end,
                       lat2 = latitude_end,
                       z1 = depth,
                       z2 = depth_end),
              by = join_by(trip_id)) |> 
    left_join(tbl_mar(con, "adb.catch_v") |> 
                group_by(station_id) |> 
                summarise(catch = sum(quantity, na.rm = TRUE),
                          .groups = "drop")) |> 
    collect(n = Inf) ->
    trips_and_tows
```

