---
title: "Sanity tests"
echo: false
message: false
warning: false
---

```{r}
library(arrow)
library(tidyverse)
library(omar)
con <- connect_mar()
# data path:
pth <- "/net/hafkaldi.hafro.is/export/home/haf/einarhj/stasi/fishydata/data/"

ais_q <- open_dataset(paste0(pth, "ais"))

ln_agf_by_vid_month_year <- 
  omar::ln_agf(con) |> 
  mutate(year = year(date),
         month = month(date)) |> 
  filter(year %in% 2009:2022,
         !between(vid, 3700 , 4999)) |> 
  group_by(vid, year, month) |> 
  summarise(catch = sum(wt) / 1e3,
            .groups = "drop") |> 
  collect() |> 
  arrange(year)

ais_by_vid_month_year <-
  ais_q |> 
  filter(vms == "yes",
         !is.na(.sid)) |> 
  mutate(year = year(time),
         month = month(time)) |> 
  count(vid, year, month) |> 
  collect()

lb <- read_rds(here::here("data/logbooks/rds/station.rds"))
lb_by_vid_month_year <- 
  lb |> 
  mutate(year = year(date),
         month = month(date)) |> 
  count(vid, month, year)
```

## Vessels


### Vessels not in stk

### Missing months in stk relative to landings

```{r}
d <- 
  full_join(ln_agf_by_vid_month_year,
            ais_by_vid_month_year) |> 
  full_join(lb_by_vid_month_year |> rename(n_lb = n)) |> 
  mutate(match = case_when(!is.na(catch) & !is.na(n_lb) & !is.na(n) ~ "ln_lb_ais",
                           # 1 missing
                           !is.na(catch) & !is.na(n_lb) &  is.na(n) ~ "ln_lb",
                           !is.na(catch) &  is.na(n_lb) & !is.na(n) ~ "ln_ais",
                            is.na(catch) & !is.na(n_lb) & !is.na(n) ~ "lb-ais",
                           # 2 missing
                            is.na(catch) &  is.na(n_lb) & !is.na(n) ~ "ais",
                            is.na(catch) & !is.na(n_lb) &  is.na(n) ~ "lb",
                           !is.na(catch) &  is.na(n_lb) &  is.na(n) ~ "ln",
                           .default = "none"))
d |> count(match)
```


```{r, fig.height = 100}
d |> 
  #filter(between(vid, 1601, 1800)) |> 
  mutate(date = ymd(paste0(year, "-", month, "-01"))) |> 
  ggplot(aes(date, factor(vid), fill = match)) +
  geom_tile() +
  scale_fill_brewer(palette = "Set1") +
  scale_x_date(date_breaks = "1 year", date_labels = "%Y")
```

```{r, eval = FALSE}
d |> 
  filter(vid == 1774) |> 
  arrange(year, month) |> 
  knitr::kable()

tmp <- 
  ais_q |> 
  filter(vid == 1621,
         year(time) == 2010,
         month(time) == 5) |> 
  collect(n = Inf)
tmp |> 
  ggplot(aes(time, speed)) +
  geom_point(size = 0.1)
tmp |> 
  arrange(time) |> 
  mutate(speed = ifelse(speed > 10, 10, speed)) |> 
  ggplot(aes(lon, lat, colour = speed)) +
  geom_point(size = 0.1) +
  scale_colour_viridis_c(option = "B", direction = 1)
library(mapdeck)
source("~/R/Pakkar2/ramb/TOPSECRET.R")
set_token(key)
ramb::rb_mapdeck(tmp |> mutate(speed = ifelse(speed > 10, 10, speed)) |> filter(vms == "yes"))
```

## Landings

## Logbooks


