project:
  type: website

website:
  title: "fishy data"
  navbar:
    left:
      - text: Documents
        menu:
          - qmd/process.qmd
          - qmd/observer-trips.qmd
          - qmd/trips.qmd
          - qmd/catch.qmd
          - qmd/auxillary-data.qmd
          - qmd/sanity-tests.qmd
          - qmd/geoserver_demo.qmd
      - text: Bits
        menu: 
          - qmd/bits_landings.qmd
    right: 
      - icon: github
        href: https://github.com/einarhjorleifsson/fishydata
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    echo: true
    message: false
    warning: false



