project:
  type: website

website:
  title: "fishy data"
  navbar:
    left:
      - text: Documents
        menu:
          - catch.qmd
          - auxillary-data.qmd
    right: 
      - icon: github
        href: https://github.com/einarhjorleifsson/fishydata
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



