project:
  type: website

website:
  title: "Fishydata"
  site-url: https://heima.hafro.is/~einarhj/fishydata
  # favicon: "image/hafro_logo.png"
  navbar:
    right:
      - text: Processing
        menu:
          - qmd/the_fishydata_process.qmd
          - ices-datacall/2025/ICES_VMS_QC-main/report-QC_format2025editNC.Rmd
      - text: On coding
        menu:
          - qmd/dataflow_dplyr_thenduckdb.qmd
          - qmd/copilot_datacall.qmd
      - ramb-list.qmd # add ramb blog to the navbar
      - icon: github
        href: https://github.com/einarhjorleifsson/fishydata

format:
  html:
    theme: flatly
    css: styles.css
    toc: false
    message: false
    warning: false
    echo: true
    code-fold: true

execute:
  freeze: auto  # re-render only when source changes
