project:
  type: website

website:
  title: "fishy data"
  navbar:
    left:
      - text: Documents
        menu:
          - process.qmd
          - trips.qmd
          - catch.qmd
          - auxillary-data.qmd
          - sanity-tests.qmd
          - geoserver_demo.qmd
    right: 
      - icon: github
        href: https://github.com/einarhjorleifsson/fishydata
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    echo: true
    message: false
    warning: false



