project:
  type: website

website:
  title: "Fishydata"
  site-url: https://heima.hafro.is/~einarhj/fishydata
  # favicon: "image/hafro_logo.png"
  navbar:
    right:
      - text: Processing
        menu:
          - qmd/the_fishydata_process.qmd
          - qmd/ices_vms_datacall.qmd
          - qmd/
      - text: On coding
        menu:
          - qmd/ices_vms_datacall.qmd
      - ramb-list.qmd # add ramb blog to the navbar
      - icon: github
        href: https://github.com/einarhjorleifsson/fishydata

format:
  html:
    theme: flatly
    css: styles.css
    toc: false
    message: false
    warning: false
    echo: true
    code-fold: true
