---
title: "Trail-landings match"
code-fold: true
message: FALSE
warning: FALSE
---

## Preamble

```{r}
library(sf)
library(mapdeck)
source("~/R/Pakkar2/ramb/TOPSECRET.R")
set_token(key)
library(tidyverse)
library(ramb)
library(omar)
con <- connect_mar()

YYYY <- 2017 

# landings ---------------------------------------------------------------------
lnd <- 
  omar::ln_agf(con) |> 
  filter(year(date) == YYYY) |> 
  collect(n = Inf) |> 
  filter(!between(vid, 3700, 4999)) |> 
  filter(vid > 0, vid != 9999) |> 
  mutate(date = as_date(date)) |> 
  group_by(vid, date, hid) |> 
  summarise(catch = sum(wt, na.rm = TRUE) / 1e3,
            .groups = "drop")
# trail ------------------------------------------------------------------------
fil <- dir("~/stasi/gis/AIS_TRAIL/trails", full.names = TRUE)
fil <- fil[str_detect(fil, paste0("y", YYYY))]
n <- nchar(fil[1])
VIDS_now <- str_sub(fil, n - 7, n-4) |> as.integer()
lnd <- lnd |> filter(vid %in% VIDS_now)
trail <- 
  map(fil, read_rds) |> 
  bind_rows()
```


```{r}
trip <- 
  trail |> 
  filter(v %in% c("end_location", "not", "short")) |> 
  arrange(vid, time) |> 
  mutate(dd = traipse::track_distance(lon, lat)) |> 
  group_by(vid, .cid) |> 
  reframe(pings = n(),
          T1 = min(time),
          T2 = max(time),
          dt = round(as.numeric(difftime(T2, T1, units = "hours")), 2),
          dd = round(sum(dd, na.rm = TRUE) / 1852, 2),
          hid_dep = hid_dep[1],
          hid_arr = hid_arr[1],
          lon1 = lon[1],
          lat1 = lat[1],
          lon2 = lon[time == T2],
          lat2 = lat[time == T2])

trip2 <- 
  trip |> 
  filter(.cid > 0,
         pings > 5,
         dt >= 1,     # trip duration [hours]
         dd > 1)      # trip distance [nm]

match <- 
  trip2 |>   # normally use trip2
  filter(vid %in% unique(lnd$vid)) |> 
  mutate(datel = as_date(T2)) |> 
  select(vid, .cid, datel, dt, dd, hid_dep, hid_arr) |>
  mutate(what = "ais") |> 
  bind_rows(lnd |> 
              # what does a landing of 0 mean
              filter(catch > 0) |> 
              mutate(what = "lnd") |> 
              rename(datel = date)) |> 
  arrange(vid, datel, what) |> 
  group_by(vid) |> 
  # if what == "ais" is followed by what == "lnd" consider that a match
  mutate(match = case_when(what == "ais" & lead(what) == "lnd" ~ TRUE,
                           what == "lnd" & lag(what) == "ais" ~ TRUE,
                           .default = FALSE),
         days = case_when(match ~ as.numeric(difftime(lead(datel), datel, units = "days")),
                          .default = NA)) |> 
  ungroup()
```


```{r}
match |> 
  filter(what == "lnd") |> 
  summarise(landings = n(),
            match = sum(match),
            no.ais.match = landings - match,
            p = round(match / landings * 100, 1)) |> 
  knitr::kable(caption = "Overall matching of trips to landings")
match |> 
  filter(what == "lnd") |> 
  # foreign harbours
  # filter(!between(hid, 160, 175)) |> 
  summarise(catch.match = sum(catch[match]),
            catch = sum(catch),
            p = round(catch.match / catch * 100, 1)) |> 
  knitr::kable(caption = "Overall matching of trips to landings - catch")
match |> 
  filter(what == "lnd") |> 
  group_by(vid) |> 
  summarise(landings = n(),
            match = sum(match),
            .groups = "drop") |> 
  mutate(all = ifelse(landings == match, "yes", "no")) |> 
  count(all) |> 
  mutate(p = round(n /sum(n), 2)) |> 
  knitr::kable(caption = "Vessels with full trip match vs partial match")

match |> 
  filter(what == "lnd") |>
  group_by(vid) |> 
  summarise(landings = n(),
            match.n = sum(match),
            dt = landings - match.n,
            p = round(match.n / landings * 100, 1),
            catch.match = sum(catch[match == TRUE]),
            catch = sum(catch),
            cdiff = catch - catch.match,
            p.catch = round(catch.match / catch * 100, 1)) |> 
  mutate(catch.match = round(catch.match, 1),
         catch = round(catch, 1),
         cdiff = round(cdiff, 1)) |> 
  arrange(p) |> 
  filter(p < 100 | p.catch < 100) |> 
  knitr::kable(caption = "Match by each vessel, arranged by proportion trips missing")
```

## Some code source

```{r}

```

