---
title: "On gear code"
author: ""
description: ""
date: "2024-12-25"
categories: []
---

## Orri - the old faithful

At MRI historical gear lookup table has been "orri.veidarfaeri". This table was kind of a hodgepodge of gear code used by the Directorate of Fisheries and the Marine Institution. The gear table contains both generic codes for commercial fishing gear (like fish trawl) as well standardized gear (like the standardized fish trawl used e.g. in the Spring Groundfish Survey). In some cases the same gear code is used for comerical gears, like shrimp trawls and nephrops trawls and more specific gear type used when surveying these two species.

To add to the confusion at one time a lot of gear codes, particularilly related to bottom trawls were added to the system but effectively not used a lot. ...

## Landing database gear code

The Directorate of Fisheries moved to a new landing database system (GAFL), with new gear code on 2007-09-01. In order to preverve the time series this system was mirrored to the old system in real time, including transforming the new gear code to the old gear code. The mapping of gear is however fully possible because in the new system there are three gear codes not in the old code system:

* "Línutregt" (): Type of line setting system
* "Sláttuprammi" (): 
